// Game-specific command handler stubs generated by StoryNodes Remake.
export const commands = {
	["OpenSmithCrafting"]: async (context) => {
		// The game supplies this handler when constructing its narrative runtime.
	},
	["OpenTravelSettings"]: async (context) => {
		// TODO: Add game-specific behavior for this command.
	}
};
