// Game-specific command handler stubs generated by StoryNodes Remake.
export const commands = {
	["OpenTravelSettings"]: async (context) => {
		// TODO: Add game-specific behavior for this command.
	}
};
